#!/usr/bin/env bash
Version="2.0.0"

# Get shared function
source "SharedFunc" || echo "Get share function fail" && exit 1

# Get color
color


script_name="$(basename "$0")"
source_path="$source_script/atsrun"
autosubcomp="$source_path/AutosubCOMP.txt"
autosubfail="$source_path/AutosubFAIL.txt"
autosubdone="$source_path/AutosubDONE.txt"
dir_config="$source_path/config"
[[ ! -d "$source_path" ]] && mkdir -p  "$source_path" && show_messenger "Created source script $source_path" "$srcipt_name"
[[ ! -d "$dir_config" ]] && mkdir -p "$dir_config" && show_messenger "Created path config $dir_config" "$srcipt_name"

atsrun=$(which autosub 2>/dev/null) || ERROR "Autosub is not installed. Please make sure it's already installed." "$script_name"

# Language support
function GetLangcode() {
	local line
	declare -A speech_LG=()
	declare -A SRC_LG=()
	while read -r line ;do
		speech_LG+=("$(echo "$line" | awk -F '  ' '{print $NF}' | sed 's/^ //g')")
		speech_LG+=("$(echo "$line" | awk -F '  ' '{print $1}' | sed 's/^ //g')")
	done < "$source_path/Speech_LG.txt"
	[[ $? -ne 0 ]] && ERROR "Get Speech Language FAIL! File not exist" "$script_name"
	while read -r line ;do
		SRC_LG+=("$(echo "$line" | awk -F '  ' '{print $NF}' | sed 's/^ //g')")
		SRC_LG+=("$(echo "$line" | awk -F '  ' '{print $1}' | sed 's/^ //g')")
	done < "$source_path/SRC_LG.txt"
	[[ $? -ne 0 ]] && ERROR "Get SRC Language FAIL! File not exist" "$script_name"
}

# Function Basename
function filebasename() {
	filename="$(basename "$1")"
	filepath="$(dirname "$1")"
	name="${filename%.*}"
}


# function config
function process_config() {
    case $1 in
        create_config ) # create new config file
			echo -e ""
			ConfigName=
			echo 
		
                        

}

function ShowProcess() {
	echo -ne "${Purple}[P]${NC} ${Lightgray}$num_process/$total_process${NC}"
	[[ -n $num_check_COMP ]] && echo -ne " | ${Green}[C]${NC} ${Lightgray}$num_check_COMP/$total_process${NC}"
	[[ -n $num_check_FAIL ]] && echo -ne " | ${Red}[F]${NC} ${Lightgray}$num_check_FAIL/$total_process${NC}"
}

# Run autosub with Audio Processing
function autosub-with-ap () {
	show_messenger "[$filename] Autosub With Audio Processing (-ap)" "$script_name"
	ShowProcess && echo ""
	"$atsrun" \
	--input "$1"  \
	--speech-language $S \
	--min-region-size $mnrs \
	--max-region-size $mxrs \
	--energy-threshold $et \
	--max-continuous-silence $mxcs \
	--not-strict-min-length \
	--drop-empty-regions \
    --format $F \
	--yes \
	--audio-process y
}

# Run autosub without Audio Processing
function autosub-without-ap () {
	show_messenger "[$filename] Autosub Without Audio Processing (no -ap)\n" "$script_name"
	ShowProcess && echo ""
	"$atsrun" \
	--input "$1"  \
	--speech-language $S \
	--min-region-size $mnrs \
	--max-region-size $mxrs \
	--energy-threshold $et \
	--max-continuous-silence $mxcs \
	--not-strict-min-length \
	--drop-empty-regions \
    --format $F \
	--yes
}

# Function Translate Subtitle
# Rename Subtitle to .srt only and Remove file Subtitle Origin
function Translate() {
echo -e "\n${LIGHTCYAN}==================================${NC}"
echo -e "         ${LIGHTCYAN}CONFIG TRANSLATE        |${NC}"
echo -e "${LIGHTCYAN}SRC Language: 	       ${YELLOW}$S${NC}     |${NC}"
echo -e "${LIGHTCYAN}Destination Language:  ${YELLOW}$d${NC}        |${NC}"
echo -e "${LIGHTCYAN}==================================${NC}\n"
echo -e "${LIGHTBLUE}Starting Translate${NC} ${YELLOW}[$filename]${NC}\n"
	$atsrun \
	--input "$1" \
	--src-language $src \
	--dst-language $d \
	--format $F \
	--yes
	sleep 0.5
	if ! mv "$filepath/$name.$S.$d.$f" "$filepath/$name.$f" 2>/dev/null ;then
	    ERROR "FAIL rename subtitle name" "$script_name"
	else
	    rm "$filepath/$name.$S.$f" 2>/dev/null
	fi
}

# Function Cleanup
function clean_temp {
	find /tmp -maxdepth 0 -type f -name "*.flac" -delete 2>/dev/null && show_messenger "Clean .flac temp completed" "$script_name" || WARNING "Having problems cleaning temp .flac" "$script_name"
	find /tmp -maxdepth 0 -type f -name "*.wav" -delete 2>/dev/null && show_messenger "Clean .wav temp completed" "$script_name" || WARNING "Having problems cleaning temp .wav" "$script_name"
    find /tmp -maxdepth 0 -type f -name "*.mov" -delete 2>/dev/null && show_messenger "Clean .mov temp completed" "$script_name" || WARNING "Having problems cleaning temp .mov" "$script_name"
	return 0
}

function CheckVideoDone() {
	if [[ $(grep -wFc "$filename" "$cptodriveCOMP") -eq 0 ]] ;then
		return 0
	else
		return 1
	fi
}

# Function create list need to handle
function CreateListFile() {
	local video
	while IFS= read -r video ;do
		if [[ -f $video ]] && CheckVideoDone || [[ -f $video ]] && [[ "$skipFile" == "yes" ]] ;then
			list_video+=("$video")
		elif [[ -f $video ]] && ! CheckVideoDone ;then
			echo "$(basename "$video")" >> "$cptodriveDONE"
			num_check_DONE+=1
		fi
	done < <(find "$1" -maxdepth 1 -type f \( -iname \*.mp4 -o -iname \*.mkv -o -iname \*.avi -o -iname \*.ts -o -iname \*.flv -o -iname \*.m4v -o -iname \*.mov -o -iname \*.wmv\) 2>/dev/null)
	[[ $? -ne 0 ]] && ERROR "Create List Video need to handle is FAIL" "$script_name"
}

function control_autosub() {
    declare -A list_video=()
	local skipAP
	first="yes"
	echo -e "Skip Audio Process? No -ap (y/n)"
	ask_user && skipAP="yes" && show_messenger "No Audio Process." "$script_name"
	echo -e "Ignore previously processed video? (y/n)"
	ask_user && skipFile="yes" && show_messenger "Ignore processed video." "$script_name"

    if [[ $# -le 1 ]] && [[ -d "$1" ]] || [[ -z "$1" ]] ;then
		if [[ -d "$1" ]] ;then
			CreateListFile "$(readlink -f "$1")"
		else
			CreateListFile "$PWD"
		fi
    else
		local file
		for file in "$@" ;do
			if [[ -d "$video" ]];then
				CreateListFile "$(readlink -f "$file")"
			else
				if CheckVideoDone || [[ "$skipFile" == "yes" ]] ;then
					list_video+=("$(readlink -f "$file")")
				else
					echo "$(basename "$file")" >> "$cptodriveDONE"
					num_check_DONE+=1
				fi
			fi
		done
    fi
	total_process=$((${#list_video[*]}-$num_check_DONE))
	echo -ne "\n${Green}TOTAL:${NC} ${Lightgray}$total_process${NC} ${Purple}Video${NC}"
	[[ -n $num_check_DONE ]] && echo -e " | ${Lightgray}$num_check_DONE${NC} ${Lightyellow}Video is DONE${NC}\n" || echo ""
	for file in "${list_video[@]}" ;do
		num_process+=1
		filebasename "$file"
		if [[ "$skipAP" == "yes" ]] ;then
			autosub-without-ap "$file"
		else
			autosub-with-ap "$file" || autosub-without-ap "$file"
		fi
		[[ $? -ne 0 ]] && ERROR "[$filename] autosub processing FAIL !" "$script_name"
		if [ -f "$filepath/$name.$S.$f" ] ;then
				Translate "$filepath/$name.$S.$f"
		else
				WARNING "[$filename] File subtitle "$name.$S.$f" not Exist !" "$script_name"
				false
		fi
		if [[ $? -ne 0 ]] && [[ ! -f "$filepath/$name.$f" ]] ;then
			WARNING "[$filename] Translate Subtitle [$name.$S.$f] Processing Fail" "$script_name"
			echo "$filename" >> "$autosubfail"
			num_check_FAIL+=1
		else
			[[ "$first" == "yes" ]] && echo "---------------------------" >> "$autosubcomp" && first="no"
			echo "$filename" >> "$autosubcomp"
			num_check_COMP+=1
		fi

		clean_temp

	done

	CheckFile

}

function CheckFile() {
	local list
	## List File Completed
	if [[ -f "$autosubcomp" ]] && [[ $num_check_COMP -gt 0 ]] ;then
	echo -e "\n${BGreen}[COMPLETED]${NC}"
	while IFS= read -r list ;do
		if [[ "$list" == "---------------------------" ]] ;then
			if [[ "$first" == "no" ]] ;then
				echo -n "$list" ;echo -e "  ${Purple}Total $num_check_COMP Video${NC} | ${Orange}$(date '+%d-%m-%Y')${NC} | ${Lightgray}$(date '+%H:%M')${NC}"
				first="stop" # Stop here
			fi
		else
			echo -e "${Green}"$list"${NC}"
		fi
	done < <(tail -n $((num_check_COMP + 2)) "$autosubcomp") 2>/dev/null
	fi
	## List File Done
	if [[ -f "$autosubdone" ]] ;then
	echo -e "\n${Yellow}[Done]${NC}"
	if [[ $num_check_DONE -gt 8 ]] ;then
		echo -e "${Purple}MORE....${NC}${Lightgray}$((num_check_DONE-8)){NC}"
		while IFS= read -r list ;do
				echo -e "${Lightyellow}$list${NC}"
		done < <(tail -n 8 "$autosubdone") 2>/dev/null
	else
		while IFS= read -r list ;do
				echo -e "${Lightyellow}$list${NC}"
		done < <(cat "$autosubdone") 2>/dev/null
	fi
	rm "$autosubdone" 2>/dev/null
	fi
	## List File Fail
	if [[ -f "$autosubfail" ]];then
	echo -e "\n${BRed}[FAIL]${NC}"
	while IFS= read -r list ;do
			echo -e "${Red}$list${NC}"
	done < <(cat "$autosubfail") 2>/dev/null
	rm "$autosubfail" 2>/dev/null
	fi

	echo ""
	ShowProcess
	echo ""
}

function menu_autosub() {

echo -e "{BWhite}    Main Menu: What would you like to do?${NC}"
echo -e "{BWhite}${NC}"
echo -e "{BWhite}Press the number of your choice:${NC}"
echo -e "{BWhite}${NC}"
echo -e "{BWhite}	1 - Autosub Japanese${NC}"
echo -e "{BWhite}	2 - Autosub Chinese (Simplified, China)${NC}"
echo -e "{BWhite}	3 - Autosub English US${NC}"
echo -e "{BWhite}	4 - Translate Subtitle (Japanese Default)${NC}"
echo -e "{BWhite}	5 - Custom Autosub${NC}"
echo -e "{BWhite}${NC}"
echo -e "{BWhite}	0 - Exit${NC}"

read -r -n 1 -s choice;

	case $choice in

		1 )  # Autosub Japanese
			control-autosub "$@"
		;;

		2 )	# Autosub Chinese (Simplified, China)
			S="cmn-hans-cn"
			src="zh-cn"
			control-autosub "$@"
		;;

		3 )	# Autosub English
			S="en-us"
			src="en"
			control-autosub "$@"
		;;

		4 )	# Translate (Japanese)
			echo -e "Config Language ?"
			if ! ask_user ;then
				for file in "$@" ;do
					# Info for Base Name
					filebasename "$file"
					# Translate Subtitle
					echo -e "${LIGHTBLUE}Translating ${YELLOW}[$filename]${NC} $S to $d ${NC}"
					if ! Translate ;then
						echo -e "${YELLOW}[$filename]${NC} ${RED}is FAIL${NC}"
						echo -e "${RED}Please Translate Again${NC}"
					else
						echo -e "\n${GREEN}Translate [$filename] is DONE${NC}"
					fi
				done
			else
				# Option for Custom Translate
				read -p -r 'Enter Video Language /src : ' src1
				# Display list SRC Support
				if [ -n "$(autosub -lsc | grep -i "$src1")" ] 2>/dev/null ;then
					autosub -lsc | grep -i "$src1"
					read -p -r 'Enter the "SRC Language" parameter as above /Ex: en-us : ' src
				else
					echo -e "${RED}Language does not exist or does not support !${NC}"
				fi
				echo
				read -p -r 'Enter Destination Language /d : ' d1
				# Display list D Support
				if [ -n "$(autosub -ltc | grep -i "$d1")" ] 2>/dev/null ;then
					autosub -ltc | grep -i "$d1"
					read -p -r 'Enter the "DST Language" parameter as above /Ex: en : ' d
				else
					echo -e "${RED}Language does not exist or does not support !${NC}"
				fi

				for file in "$@" ;do
					# Info for Base Name
					filebasename "$file"
					# Translate Subtitle
					echo -e "${LIGHTBLUE}Translating ${YELLOW}[$filename]${NC} $S to $d ${NC}"
					if ! Translate ;then
						echo -e "${YELLOW}[$filename]${NC} ${RED}is FAIL${NC}"
						echo -e "${RED}Please Translate Again${NC}"
					else
						echo -e "\n${GREEN}Translate [$filename] is DONE${NC}"
					fi
				done
			fi
			clear
		;;

		5 ) # Custom
			while true
				do
					constan
					custom-autosub
					config
					echo -e "${LIGHTCYAN}Check and start autosub ! (y/n)${NC}"
					! ask_user || continue 0
			done
			control-autosub "$@"
		;;

		0 )	# Break Menu
			echo -e "\n${LIGHTCYAN}DONE ALL${NC}"
			echo -e "${LIGHTCYAN}THANK YOU FOR USING${NC}"
			clear
			exit 0
		;;

		* )	# Not Valid Choice
			clear
			echo -e "\n${RED}Not a valid choice${NC}"
			echo -e "${RED}Please choice some number${NC}\n"
			menuAutosub "$@"
		;;

	esac

} 



